### ISSUE TITLE
[Bug] - Cannot Add Channels That Do Not Have user, u, or c

### ISSUE THREAD

**Issue by hxrsmurf** [hxrsmurf/ytdlp-flask-nextjs#42]
I've noticed some channels do not have the `user`, `u`, or `c` in their channel URLs. This gives an error when trying to download the channel and therefore is not added to the database. 

An example is: `https://www.youtube.com/ChessNetworkTV`

We should check why this is happening and provide a workaround.

**Comment by hxrsmurf** [comment]
This is the error in the backend:

```
[2022-07-31 05:45:11,416] ERROR in app: Exception on /mongo/videos/add [GET]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\kvchm\repos\ytdlp-flask-nextjs\backend\blueprints\mongo.py", line 125, in add_videos
    duration = download_result['duration'],
KeyError: 'duration'
```

**Comment by hxrsmurf** [comment]
It actually returns a `playlist`
